config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root 'static_pages#index'
  
  get   '/users/'                                   => 'users#index'
  get   'edit'                                      => 'users#edit'
  patch 'edit'                                      => 'users#update'
  get   '/users/:id'                                => 'users#show',      as: 'user_show'


  get   '/companies'                                => 'companies#index', as: 'companies'
  get   '/companies/:stock_exchange'                => 'companies#index'
  get   '/companies/:stock_exchange/:symbol'        => 'companies#show',  as: 'company'

  get   '/airlines'                                 => 'airlines#index',  as: 'airlines'
  get   '/airlines/:icao'                           => 'airlines#show',   as: 'airline'

  get   '/airplanes'                                => 'airplanes#index', as: 'airplanes'
  get   '/airplanes/:airline_iata/:registration_code' => 'airplanes#show',  as: 'airplane'

  end

app/models/airline.rb
class Airline < ActiveRecord::Base

  has_many :airplanes
end

app/models/airplane.rb
class Airplane < ActiveRecord::Base

  belongs_to :airline
end

app/models/annualincome.rb
class Annualincome < ActiveRecord::Base

  belongs_to :company

end

app/models/company.rb
class Company < ActiveRecord::Base

  has_many :annualincomes
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    :storage => :s3,
                    :s3_credentials => Proc.new{|a| a.instance.s3_credentials },
                    :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "https://s3.amazonaws.com/predikt-app/missing.jpg"

  validates_attachment_content_type :avatar, 
                                    :content_type => /\Aimage\/.*\Z/

  # validates :username, uniqueness: true

  def s3_credentials
    {
      :bucket => ENV['S3_BUCKET'],
      :access_key_id => ENV['S3_ACCESS_KEY_ID'],
      :secret_access_key => ENV['S3_SECRET_ACCESS_KEY']
    }
  end
end

app/controllers/airlines_controller.rb
class AirlinesController < ApplicationController

  before_action :authenticate_user!

  def index
    @airlines = Airline.all
  end

  def show
    @airline = Airline.find_by(:icao => params[:icao])
  end

end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController

  before_action :authenticate_user!
  
  def index
    @airplanes = Airplane.all
  end

  def show
    @airline = Airline.find_by(:iata => params[:airline_iata])
    @airplane = @airline.airplanes.find_by(:registration_code => params[:registration_code])
  end

end

app/controllers/annualincomes_controller.rb
class AnnualincomesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @companies = params[:stock_exchange] ? Company.where(:stock_exchange => params[:stock_exchange]) : Company.all
  end

  def show
    @company = Company.find_by(:stock_exchange => params[:stock_exchange], :symbol => params[:symbol])
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :authenticate_user!, only: [:new, :editprofile]

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(:id => params[:id])
    if @user.nil?
      # head 402
      # head 406
      redirect_to :root, flash: { error: 'User doesn\'t exist.' }
    else
      render :show
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update_attributes( :avatar => user_params[:avatar], 
                             :first_name => user_params[:first_name],
                             :last_name => user_params[:last_name],
                             :username => user_params[:username] )
    redirect_to user_show_url(current_user)
  end

  private

  # Use strong_parameters for attribute whitelisting
  # Be sure to update your create() and update() controller methods.

  def user_params
    params.require(:user).permit(:avatar, :first_name, :last_name, :username)
  end

end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/helpers/annualincomes_helper.rb
module AnnualincomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
    current_page?(link_path) ? "active" : ""
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/airlines/index.html.erb
<div class="row">
  <h1>List of Airlines</h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>ICAO</th>
          <th>IATA</th>
          <th>Airline Name</th>
          <th>Number of Listed Airplanes</th>
        </tr>
      </thead>
      <tbody>
        <% @airlines.each do |airline| %>
          <tr>
            <% if airline.airplanes.empty? %>
              <td><%= airline.icao %></td>
            <% else %>
              <td><%= link_to airline.icao, airline_path(airline.icao) %></td>
            <% end %>
            <td><%= airline.iata %></td>
            <td><%= airline.name %></td>
            <td><%= airline.airplanes.count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/airlines/show.html.erb
<div class="row">
  <h1><%= @airline.name %></h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>IATA Code</th>
          <th>ICAO Code</th>
          <th>Number of Active Airplaines</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @airline.iata %></td>
          <td><%= @airline.icao %></td>
          <td><%= @airline.airplanes.count %></td>
        </tr>
      </tbody>
    </table>
  </div>
    
  <h2>List of Airplanes</h2>
  <% if @airline.airplanes.empty? %>
    <p>No Airplaines listed yet</p>
  <% else %>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th>Registration Code</th>
            <th>Type</th>
            <th>Type Code</th>
            <th>ModeS</th>
            <th>S/N</th>
          </tr>
        </thead>
        <tbody>
          <% @airline.airplanes.each do |airplane| %>
            <tr>
              <td><%= link_to airplane.registration_code, airplane_path(@airline.iata, airplane.registration_code) %></td>
              <td><%= airplane.plane_type %></td>
              <td><%= airplane.plane_type_code %></td>
              <td><%= airplane.mode_s %></td>
              <td><%= airplane.s_n %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/airplanes/show.html.erb
<div class="row">
  <h1><%= @airplane.registration_code %></h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Registration Code</th>
          <th>Type</th>
          <th>Type Code</th>
          <th>ModeS</th>
          <th>S/N</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @airplane.registration_code %></td>
          <td><%= @airplane.plane_type %></td>
          <td><%= @airplane.plane_type_code %></td>
          <td><%= @airplane.mode_s %></td>
          <td><%= @airplane.s_n %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div><%= link_to "Back to #{@airline.name}", airline_path(@airline.icao) %></div>
  <div><%= link_to "Back to the list of Airlines", airlines_path %></div>
</div>

app/views/companies/index.html.erb
<div class="row">
  <h1>List of Companies</h1>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Stock Exchange</th>
          <th>Symbol</th>
          <th>Company Name</th>
        </tr>
      </thead>
      <tbody>
        <% @companies.each do |company| %>
          <tr>
            <td><%= company.stock_exchange %></td>
            <% if company.annualincomes.empty? %>
              <td><%= company.symbol %></td>
            <% else %>
              <td><%= link_to company.symbol, company_path(company.stock_exchange, company.symbol) %></td>
            <% end %>
            <td><%= company.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/companies/show.html.erb
<div class="row">
  <h1><%= @company.name %></h1>

  <% if @company.annualincomes.empty? %>
    <p>No accounts are listed for this company yet.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
            <th><%= @company.annualincomes[0]['currency'] %></th>
            <% @company.annualincomes.each do |annualincome| %>
              <th><%= annualincome['period'] %></th>
            <% end %>    
          </tr>
      </thead>
      <tbody>
        <% Annualincome.columns[4..52].each_with_index do |column, index| %>
          <tr>
            <td><%= column.name.humanize.split.map(&:capitalize).join(' ') %></td>
            <% @company.annualincomes.each do |annualincome| %>
              <td><%= annualincome[column.name] %></td>
            <% end %>    
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<ul class="nav nav-tabs">

  <li role="presentation" class="<%= is_active?(root_path) %>">
    <%= link_to "Home", root_path %>
  </li>
  <li role="presentation" class="<%= is_active?(users_path) %>">
    <%= link_to "List of Users", users_path %>
  </li>
  <!-- <li role="presentation" class="<%= is_active?(companies_path) %>">
    <%= link_to "List of Companies", companies_path %>
  </li>
  <li role="presentation" class="<%= is_active?(airlines_path) %>">
    <%= link_to "List of Airlines", airlines_path %>
  </li> -->
  <!-- <li role="presentation" class="<%= is_active?(airplanes_path) %>">
    <%= link_to "List of Airplanes", airplanes_path %>
  </li> -->
  
  <% if current_user %>
    <li role="presentation" class="nav-right <%= is_active?(destroy_user_session_path) %>">
      <%= link_to "Sign Out", destroy_user_session_path, :method => 'delete' %>
    </li>
    <!-- <li role="presentation" class="nav-right <%= is_active?(edit_user_registration_path) %>">
      <%= link_to "Update Password", edit_user_registration_path %>
    </li> -->
    <li role="presentation" class="nav-right <%= is_active?(edit_path) %>">
      <%= link_to "Edit Profile", edit_path %>
    </li>
    <li role="presentation" class="nav-right <%= is_active?(user_show_path(current_user)) %>">
      <%= link_to "My Profile", user_show_path(current_user) %>
    </li>
  
  <% else %>
    <li role="presentation" class="nav-right <%= is_active?(new_user_registration_path) %>">
      <%= link_to "Sign Up", new_user_registration_path %>
    </li>
    <li role="presentation" class="nav-right <%= is_active?(new_user_session_path) %>">
      <%= link_to "Log In", new_user_session_path %>
    </li>
  <% end %>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PLD</title>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  
  <body class="body">
    <div class="container">
      <header>
        <%= render :partial => 'layouts/header' %>
      </header>

    <% flash.each do |name, msg| %>
      <script type='text/javascript'>
        notyMessage("<%= name %>","<%= msg %>");
      </script>
    <% end %>

    <main role="main" class="main">
      <%= yield %>
    </main>

    </div>
  </body>
</html>

app/views/static_pages/index.html.slim
h1.title Hello World

app/views/users/edit.html.erb
<div>
  <%= link_to "Go to Update my Password", edit_user_registration_path, :class => "btn btn-default" %>
</div>

<h1>Add a picture to your profile</h1>

<%= simple_form_for @user, url: edit_path, html: { :multipart => true } do |f| %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :username %> <span>(has to be unique)</span>
  </div>
  <div class="form-group">
    <%= f.label "picture upload" %>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/users/index.html.erb
<div class="row">
  <h1>List of Users</h1>
  <% @users.each do |user| %>
    <div class="col-md-4">
      <%= image_tag user.avatar.url(:medium), :class => "img-circle" %>
      <p class="list-users-name"><%= user.first_name %> <%= user.last_name %></p>
      <p class="list-users-email"><%= user.email %></p>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<h1>User: <%= @user.first_name %> <%= @user.last_name %></h1>
<div><%= @user.email %></div>
<div><%= image_tag @user.avatar.url(:medium) %></div>